<a href="https://colab.research.google.com/github/FernandaGarciaCamacho/mineria-de-datos/blob/main/Mineria_de_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mineria de Datos

## Primer Parcial

### Introducción

#### Conceptos

##### Mineria de datos



Actividad para extracción de datos, donde se busca encontrar patrónes de datos para a su vez optimizar actividades. Se utiliza para procesar y explorar grandes conjuntos de datos. Es el proceso de analizar grandes volúmenes de datos para descubrir patrones, anomalías y correlaciones ocultas, transformando así datos brutos en conocimiento valioso para la toma de decisiones estratégicas, la predicción de tendencias y la optimización de procesos en diversas industrias, utilizando técnicas de estadística, inteligencia artificial y aprendizaje automático.

##### Ciencia de Datos

La ciencia de datos es el estudio de datos con el fin de extraer información significativa. Es el estudio científico de los datos para obtener conocimientos. La Ciencia de Datos es un campo multidisciplinario que combina estadística, matemáticas, inteligencia artificial y computación para analizar grandes volúmenes de datos y extraer conocimiento significativo, patrones y tendencias, con el fin de apoyar la toma de decisiones, hacer predicciones y resolver problemas en diversas industrias.

#### Ciencia de Datos

In [ ]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
len?

In [ ]:
L = [1, 2, 3]

In [ ]:
L?

In [ ]:
def square(a):
  """Return the square of a."""
  return a ** 2

In [ ]:
square?

In [ ]:
square??

In [ ]:
len??

In [ ]:
L.append

<function list.append(object, /)>

In [ ]:
L.clear

<function list.clear()>

In [ ]:
L.count

<function list.count(value, /)>

In [ ]:
L.__add__

<method-wrapper '__add__' of list object at 0x7f3cf43e7700>

In [ ]:
from itertools import combinations

In [ ]:
import h11

In [ ]:
*Warning?

In [ ]:
str.*find*?

IPython Magic Commands

In [ ]:
#El comando magico sirve para evaluar el desempeño en terminos de tiempo
%timeit L = [n ** 2 for n in range(1000)]

68.8 µs ± 1.32 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
#El comando magico tambien sirve para evaluar el desempeño, solo que este abarca
#varias lineas de codigo en lugar de una
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

76.7 µs ± 1.18 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


IPython and Shell Commands

In [ ]:
!ls

sample_data


In [ ]:
#El % te conserva ahi, ! solo es para visualizar una vez y no te conserva ahi

%cd sample_data/

[Errno 2] No such file or directory: 'sample_data/'
/content/sample_data


In [ ]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [ ]:
!cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [ ]:
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': '4422516dc7cd',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

Understanding Data Types in Python

In [ ]:
import numpy as np

In [ ]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [ ]:
#Crea un rango tomando desde i hasta i+3 (sin tomar en cuenta el ultimo)
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

The basics of NumPy Arrays

In [1]:
import numpy as np

In [2]:
np.random.seed(0)  # seed for reproducibility

In [3]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [4]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [5]:
print(x2.dtype)

int64


In [6]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


Array Indexing: Accessing Single Elements

In [7]:
x1

array([5, 0, 3, 3, 7, 9])

In [10]:
x1[0] #Colocamos el indice del elemento a extraer, en este caso el primer elemento tiene el indice 0

np.int64(5)

In [11]:
x1[4]

np.int64(7)

In [12]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [13]:
x2[0,0]

np.int64(3)

In [14]:
x2[0,2]

np.int64(2)

In [15]:
x2[2,-1]

np.int64(7)

In [17]:
x2[0,0]=12 #Asigna nuevos valores a la posición
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

####Estadistica Básica

In [18]:
import numpy as np

Media (Mean)

In [19]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


Promedio (Average) y Promedio Ponderado

In [20]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

Mediana

In [21]:
mediana = np.median(data)

Varianza y Desviación Estándar

In [23]:
varianza = np.var(data)
desviacion = np.std(data)

Generación de Datos Aleatorios

In [24]:
muestra = np.random.normal(0, 1, 1000)
print(np.mean(muestra), np.std(muestra))

-0.006543456960417206 1.0059985778093545


Correlación

In [25]:
corr = np.corrcoef([1,2,3], [1,5,7])